# server {
#     listen 80;
#     server_name cms.*;
#     http2  on;

#     access_log $strapi_access_log;
#     error_log $strapi_debug_log;

#     # Relay traffic to upstream strapiApp
#     location / {

#         proxy_pass https://strapiApp;
#         proxy_pass_request_headers on;
#         proxy_set_header Host $host;
#         proxy_set_header X-Real-IP $remote_addr;
#         proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
#         proxy_set_header X-Forwarded-Proto $scheme;
#         proxy_ssl_server_name on;
#         proxy_hide_header X-Powered-By;
#         proxy_set_header Connection keep-alive;
#         # Headers to support WebSocket connections and upgrades
#         proxy_http_version 1.1;
#         proxy_set_header Upgrade $http_upgrade;
#         proxy_set_header Connection "upgrade";

#         access_log $strapi_access_log;
#         error_log $strapi_debug_log;
#     }

#     # Deny access to .htaccess files
#     location ~ /\.ht {
#         deny all;
#         access_log $access_log_path;
#         error_log $error_log_path;
#     }
# }

server {
    listen 80;
    server_name dev.cms.*;

    access_log $strapi_access_log;
    error_log $strapi_error_log;

    # Relay traffic to upstream devstrapiApp
    location / {

        proxy_pass http://devStrapiApp;
        proxy_pass_request_headers on;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
        proxy_ssl_server_name on;
        proxy_hide_header X-Powered-By;
        proxy_set_header Connection keep-alive;
        proxy_http_version 1.1;
        access_log $strapi_access_log;
        error_log $strapi_debug_log;
    }

    location /admin {
        proxy_pass http://hmrStrapiApp; # Vite HMR server
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
        proxy_hide_header X-Powered-By;
        access_log $strapi_access_log;
        error_log $strapi_debug_log;  
    }

}