enableColors: true

nodeLinker: node-modules

packageExtensions:
  #Strapi packages
  "@strapi/core@*":
    dependencies:
      "@strapi/strapi": "*"
  "@strapi/content-type-builder@*":
    dependencies:
      "@strapi/types": "*"
  "@strapi/review-workflows@*":
    dependencies:
      "lodash": "*"
      "semver": "*"
      "@strapi/types": "*"
      "date-fns": "*"
  "@strapi/plugin-users-permissions@*":
    dependencies:
      "@strapi/strapi": "*"
      "@strapi/utils": "*"
  "knex@*":
    dependencies:
      "mysql2": "*"
  "@strapi/admin@*":
    dependencies:
      "@strapi/data-transfer": "*"
  "@strapi/upload@*":
    dependencies:
      "strapi-provider-upload-azure-storage": "*"
  "@strapi/design-system@*":
    dependencies:
      "@codemirror/state": "*"
      "@codemirror/view": "*"
  "esbuild-register@*":
    peerDependencies:
      "esbuild": "*"
