name: Setup Pulumi CLI and Yarn
runs:
  using: "composite"
  steps:
    - name: Install Pulumi CLI
      uses: pulumi/setup-pulumi@v2
    - name: Install Pulumi Node.js SDK dependencies
      run: yarn install --immutable
      working-directory: ./azure-deploy
      shell: bash
