name: Setup Node, Corepack, and Yarn
runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@v4
      with:
        node-version-file: ./azure-deploy/package.json
    - run: corepack enable
      shell: bash
    - run: |
        for i in 1 2 3 4 5; do
          corepack prepare yarn@4.9.1 --activate && break || sleep 10
        done
      shell: bash
