[supervisord]
nodaemon=true
logfile=/dev/stdout
logfile_maxbytes=0
logfile_backups=0
loglevel=info
pidfile=/tmp/supervisord.pid

[program:strapi-backend]
directory=/opt/app
command=npm run develop:api
autostart=true
autorestart=true
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
user=node
environment=NODE_ENV="development"

[program:vite-admin]
directory=/opt/app/src/admin
command=npm run develop:admin:debug
autostart=true
autorestart=true
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
user=node
environment=NODE_ENV="development"
