environment:
  - marketing/test
config:
  marketing:adminJwtSecret:
    secure: AAABAHZyukivOM7wkmUCMbpb6wx7sUl0okLtqHECMLxnMH/nriBGoEw8E9bb34pCfn85nrNFSRvXlPs/5IDA0vpw3oi/FPXc40Y5v52bWpt6TkwmQQ2uXm0Zgks56JXe
  marketing:jwtSecret:
    secure: AAABAIUdYS8urmOE/wA7Eo6aDsmaf+Jvc7wJEvQ+VGXgKqaGRg6cWM3HBzEYPnEfDI+PRVetL72SFyezoFYelo+ju2rLmVPdZN7EmSgg74Fo4ySxQM1YpAnTbQWXpcIV
  marketing:appKeys:
    secure: AAABAFOAwJgOE3FserW5eAwYcoY7/4GCXBgBDT5hH7+VSgPXL607v8Rmk2i/W2sQF++zUV2JcqqH2bLAbO1oRgxjRR7RqhnzN5QEyOBbLqYK7BZZWEhN3sisMQtctuc+/fATE4+36PGadEvDIuS4RoPvOM7aaGMkrtMSVqIsk2lOZfPcDLN9x/ldvu/m8I7PKiXJ5WaJPzsXpBs0ZvfO435g3jNnPrTXO1GuH1NvkRdAdU5ixJQB7Ev8gdMVl2nxSeDzFKweqsuotl/qKQSP/RnjWMhROX3420gquhx0tvH/sw==
  marketing:strapiDbName: strapi
  marketing:apiToken: 012053280630164e2436582d44f362d5cbd7dc94752cb232051984a905705289
