FROM php:8.3-apache

# Install required packages and PHP extensions
RUN apt-get update && apt-get install -y \
    libpng-dev \
    libjpeg-dev \
    libfreetype6-dev \
    libonig-dev \
    libzip-dev \
    unzip \
    curl \
    libc-client-dev \
    libkrb5-dev \
    && docker-php-ext-configure gd --with-freetype --with-jpeg \
    && docker-php-ext-configure imap --with-kerberos --with-imap-ssl \
    && docker-php-ext-install gd zip mysqli imap

# Copy application files
COPY ./vtigercrm /var/www/html/

# Turn off display errors in php
RUN echo "display_errors = Off" >> /usr/local/etc/php/php.ini


# Set permissions for Apache
RUN chown -R www-data:www-data /var/www/html && \
    chmod -R 755 /var/www/html

# Expose the port Vtiger uses
EXPOSE 80

CMD ["apache2-foreground"]
