name: Deploy
permissions:
  id-token: write
  contents: read
on:
  push:
    branches:
      - master
jobs:
  
  setup-acr-infra:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/catthehacker/ubuntu:js-22.04
    strategy:
      matrix:
        env_esc: ${{ fromJson(vars.ESC) }}
    env:
      ENV_ESC: ${{ matrix.env_esc }}
      PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Install Pulumi CLI
        uses: pulumi/setup-pulumi@v2
      - name: Enable Corepack (Yarn 4+)
        run: corepack enable
      - uses: actions/cache@v3
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: |
            .yarn/cache
            .yarn/install-state.gz
            .yarn/unplugged
            .yarn/build-state.yml
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Install Node.js dependencies
        run: yarn install --immutable
        working-directory: .
      - name: Install Azure CLI
        run: |
          curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
      - name: Run Pulumi Automation API for ACR infra and export outputs
        id: pulumi-acr
        working-directory: ./azure-deploy
        env:
          GITHUB_JOB: setup-acr-infra
          ENV_ESC: ${{ matrix.env_esc }}
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
          ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
        run: |
          # Stack name: organization/environment/setup-acr-infra
          ORG=$(echo "$ENV_ESC" | awk -F'/' '{print $1}')
          PROJECT=$(echo "$ENV_ESC" | awk -F'/' '{print $2}')
          ENV=$(echo "$ENV_ESC" | awk -F'/' '{print $3}')
          STACK_NAME="$ORG/$ENV/setup-acr-infra"
          echo "Using stack: $STACK_NAME"
          PULUMI_OUTPUTS=$(npx ts-node index.ts --stack "$STACK_NAME")
          echo "PULUMI_OUTPUTS=$PULUMI_OUTPUTS" >> $GITHUB_ENV
          echo "ACR_USERNAME=$(jq -r .acrUsernameOut $PULUMI_OUTPUTS)" >> $GITHUB_ENV
          echo "ACR_PASSWORD=$(jq -r .acrPasswordOut $PULUMI_OUTPUTS)" >> $GITHUB_ENV
          echo "ACR_URL=$(jq -r .registryUrlOut $PULUMI_OUTPUTS)" >> $GITHUB_ENV
  setup-infra:
    needs: setup-acr-infra
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/catthehacker/ubuntu:js-22.04
    strategy:
      matrix:
        env_esc: ${{ fromJson(vars.ESC) }}
    env:
      ENV_ESC: ${{ matrix.env_esc }}
      PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Install Pulumi CLI
        uses: pulumi/setup-pulumi@v2
      - name: Enable Corepack (Yarn 4+)
        run: corepack enable
      - uses: actions/cache@v3
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: |
            .yarn/cache
            .yarn/install-state.gz
            .yarn/unplugged
            .yarn/build-state.yml
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Install Node.js dependencies
        run: yarn install --immutable
        working-directory: ./azure-deploy
      - name: Install Azure CLI
        run: |
          curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash

      - name: Run Pulumi Automation API for infra
        working-directory: ./azure-deploy
        env:
          GITHUB_JOB: setup-infra
          ENV_ESC: ${{ matrix.env_esc }}
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
          ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
        run: |
          ORG=$(echo "$ENV_ESC" | awk -F'/' '{print $1}')
          PROJECT=$(echo "$ENV_ESC" | awk -F'/' '{print $2}')
          ENV=$(echo "$ENV_ESC" | awk -F'/' '{print $3}')
          STACK_NAME="$ORG/$ENV/setup-infra"
          echo "Using stack: $STACK_NAME"
          npx ts-node index.ts --stack "$STACK_NAME"

  build-images:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/catthehacker/ubuntu:act-22.04
    strategy:
      matrix:
        include:
          - name: marketing-nginx
            dockerfile: mautic/marketing-nginx.dockerfile
          - name: marketing-mautic-app
            dockerfile: mautic/marketing-mautic-app.dockerfile
          - name: marketing-strapi-app
            dockerfile: launchpad/Dockerfile.prod
          - name: marketing-suitecrm-app
            dockerfile: suitecrm/marketing-suitecrm-app.dockerfile
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Cache Docker layers
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ matrix.name }}-${{ hashFiles(matrix.dockerfile) }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      - name: Build Docker image
        run: |
          docker buildx create --use
          docker buildx build \
            --load \
            --cache-from=type=local,src=/tmp/.buildx-cache \
            --cache-to=type=local,dest=/tmp/.buildx-cache \
            -t ${{ matrix.name }}:build \
            -f ${{ matrix.dockerfile }} .
  push-images:
    needs: [build-images, setup-acr-infra]
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/catthehacker/ubuntu:act-22.04
    env:
      ENV_ESC: ${{ vars.ESC }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Get ACR outputs from Pulumi stack
        id: acr-outputs
        working-directory: ./azure-deploy
        env:
          ENV_ESC: ${{ env.ENV_ESC }}
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
          ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
        run: |
          ORG=$(echo "$ENV_ESC" | awk -F'/' '{print $1}')
          ENV=$(echo "$ENV_ESC" | awk -F'/' '{print $3}')
          STACK_NAME="$ORG/$ENV/setup-acr-infra"
          pulumi stack output --stack "$STACK_NAME" --json > acr-outputs.json
          echo "ACR_USERNAME=$(jq -r .acrUsernameOut acr-outputs.json)" >> $GITHUB_ENV
          echo "ACR_PASSWORD=$(jq -r .acrPasswordOut acr-outputs.json)" >> $GITHUB_ENV
          echo "ACR_URL=$(jq -r .registryUrlOut acr-outputs.json)" >> $GITHUB_ENV
      - name: Login to Azure Container Registry
        run: echo ${{ needs.setup-acr-infra.outputs.ACR_PASSWORD }} | docker login ${{ needs.setup-acr-infra.outputs.ACR_URL }} -u ${{ needs.setup-acr-infra.outputs.ACR_USERNAME }} --password-stdin
      - name: Tag and push Docker images
        run: |
          docker tag marketing-nginx:build "$ACR_URL"/marketing-nginx:latest
          docker tag marketing-mautic-app:build "$ACR_URL"/marketing-mautic-app:latest
          docker tag marketing-strapi-app:build "$ACR_URL"/marketing-strapi-app:latest
          docker tag marketing-suitecrm-app:build "$ACR_URL"/marketing-suitecrm-app:latest
          docker push "$ACR_URL"/marketing-nginx:latest
          docker push "$ACR_URL"/marketing-mautic-app:latest
          docker push "$ACR_URL"/marketing-strapi-app:latest
          docker push "$ACR_URL"/marketing-suitecrm-app:latest
