name: Deploy
permissions:
  id-token: write
  contents: read
on:
  push:
    branches:
      - master
jobs:
  
  setup-acr-infra:
    runs-on: ubuntu-latest
    container: ghcr.io/ajwtech/marketforge-ci:latest
    strategy:
      matrix:
        env_esc: ${{ fromJson(vars.ESC) }}
    env:
      ENV_ESC: ${{ matrix.env_esc }}
      PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: actions/cache@v3
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: |
            .yarn/cache
            .yarn/install-state.gz
            .yarn/unplugged
            .yarn/build-state.yml
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Install Node.js dependencies
        run: yarn install --immutable
        working-directory: .

      - name: Run Pulumi Automation API for ACR infra and export outputs
        id: pulumi-acr
        working-directory: ./azure-deploy
        env:
          GITHUB_JOB: setup-acr-infra
          ENV_ESC: ${{ matrix.env_esc }}
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
          ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
        run: |
          npx ts-node index.ts
          
  setup-infra:
    needs: setup-acr-infra
    runs-on: ubuntu-latest
    container: ghcr.io/ajwtech/marketforge-ci:latest
    strategy:
      matrix:
        env_esc: ${{ fromJson(vars.ESC) }}
    env:
      ENV_ESC: ${{ matrix.env_esc }}
      PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: actions/cache@v3
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: |
            .yarn/cache
            .yarn/install-state.gz
            .yarn/unplugged
            .yarn/build-state.yml
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Install Node.js dependencies
        run: yarn install --immutable
        working-directory: ./azure-deploy

      - name: Run Pulumi Automation API for infra
        working-directory: ./azure-deploy
        env:
          GITHUB_JOB: setup-infra
          ENV_ESC: ${{ matrix.env_esc }}
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
          ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
        run: |
          npx ts-node index.ts

  build-images:
    runs-on: ubuntu-latest
    container: docker:latest
    strategy:
      matrix:
        include:
          - name: marketing-nginx
            dockerfile: mautic/marketing-nginx.dockerfile
          - name: marketing-mautic-app
            dockerfile: mautic/marketing-mautic-app.dockerfile
          - name: marketing-strapi-app
            dockerfile: launchpad/Dockerfile.prod
          - name: marketing-suitecrm-app
            dockerfile: suitecrm/marketing-suitecrm-app.dockerfile
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ matrix.name }}-${{ hashFiles(matrix.dockerfile) }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      - name: Set image tag from commit SHA
        run: echo "IMAGE_TAG=${GITHUB_SHA}" >> $GITHUB_ENV
      - name: Build Docker image
        run: |
          docker buildx create --use
          docker buildx build \
            --load \
            --cache-from=type=local,src=/tmp/.buildx-cache \
            --cache-to=type=local,dest=/tmp/.buildx-cache \
            -t ${{ matrix.name }}:${{ env.IMAGE_TAG }} \
            -f ${{ matrix.dockerfile }} .
        env:
          IMAGE_TAG: ${{ github.sha }}
      - name: Save Docker image as artifact
        run: |
          docker save ${{ matrix.name }}:${{ env.IMAGE_TAG }} -o ${{ matrix.name }}-${{ env.IMAGE_TAG }}.tar
        env:
          IMAGE_TAG: ${{ github.sha }}
      - name: Upload Docker image artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.name }}-image-${{ github.sha }}
          path: ${{ matrix.name }}-${{ github.sha }}.tar

  push-images:
    needs: [build-images, setup-acr-infra]
    runs-on: ubuntu-latest
    container: docker/docker:latest
    env:
      ENV_ESC: ${{ matrix.env_esc }}
      PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
    strategy:
      matrix:
        env_esc: ${{ fromJson(vars.ESC) }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive 
      - name: Download Docker image artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./images
      - name: Load Docker images
        run: |
          for tar in ./images/*/*.tar; do
            docker load -i "$tar"
          done
      - name: Login to Azure Container Registry
        run: |
          ORG_PROJECT=$(echo "$ENV_ESC" | awk -F'/' '{print $1 "/" $2}')
          ACR_STACK_NAME="setup-acr-infra"
          FULL_STACK="$ORG_PROJECT/$ACR_STACK_NAME"
          pulumi stack output acrPasswordOut --show-secrets -s "$FULL_STACK" | \
          docker login \
            "$(pulumi stack output registryUrlOut -s "$FULL_STACK")" \
            -u "$(pulumi stack output acrUsernameOut -s "$FULL_STACK")" \
            --password-stdin
      - name: Tag and push Docker images
        run: |
          IMAGE_TAG=${GITHUB_SHA}
          ORG_PROJECT=$(echo "$ENV_ESC" | awk -F'/' '{print $1 "/" $2}')
          ACR_STACK_NAME="setup-acr-infra"
          FULL_STACK="$ORG_PROJECT/$ACR_STACK_NAME"
          acrUrlOut=$(pulumi stack output registryUrlOut -s "$FULL_STACK")
          az acr login --name $(echo "$acrUrlOut" | awk -F'.' '{print $1}')

          for image in marketing-nginx marketing-mautic-app marketing-strapi-app marketing-suitecrm-app; do
            repo="$acrUrlOut/$image"
            # Check if tag exists in ACR
            if az acr repository show-tags --name $(echo "$acrUrlOut" | awk -F'.' '{print $1}') --repository $image --query "[?@=='$IMAGE_TAG']" -o tsv | grep -q "$IMAGE_TAG"; then
              echo "$repo:$IMAGE_TAG already exists in ACR, skipping push."
            else
              docker tag $image:$IMAGE_TAG $repo:$IMAGE_TAG
              docker push $repo:$IMAGE_TAG
            fi
          done
  setup-apps:
    needs: [setup-infra, push-images]
    runs-on: ubuntu-latest
    container: ghcr.io/ajwtech/marketforge-ci:latest
    strategy:
      matrix:
        env_esc: ${{ fromJson(vars.ESC) }}
    env:
      ENV_ESC: ${{ matrix.env_esc }}
      PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: actions/cache@v3
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: |
            .yarn/cache
            .yarn/install-state.gz
            .yarn/unplugged
            .yarn/build-state.yml
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Install Node.js dependencies
        run: yarn install --immutable
        working-directory: ./azure-deploy

      - name: Run Pulumi Automation API for infra
        working-directory: ./azure-deploy
        env:
          GITHUB_JOB: setup-apps
          ENV_ESC: ${{ matrix.env_esc }}
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
          ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
        run: |
          npx ts-node index.ts