name: Deploy
permissions:
  id-token: write
  contents: read
on:
  push:
    branches:
      - master
jobs:
  setup-environment:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/catthehacker/ubuntu:act-22.04
    strategy:
      matrix:
        env_esc: ${{ fromJson(vars.ESC) }}
    env:
      ENV_ESC: ${{ matrix.env_esc }}
    outputs:
      FULL_STACK: ${{ steps.set-stack-vars.outputs.FULL_STACK }}
      TRIMMED_STACK: ${{ steps.set-stack-vars.outputs.TRIMMED_STACK }}
      ESC_ENVIRONMENT: ${{ steps.set-stack-vars.outputs.ESC_ENVIRONMENT }}
      ORGANIZATION: ${{ steps.set-stack-vars.outputs.ORGANIZATION }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: ./.github/actions/setup-node-yarn

      - name: Authenticate with Pulumi Cloud
        uses: pulumi/auth-actions@v1
        with:
          organization: ajwtech
          requested-token-type: urn:pulumi:token-type:access_token:personal
      - name: Install and inject ESC environment variables
        uses: pulumi/esc-action@v1
        with:
          environment: 'tinyco/someProject/myEnv'
      - name: Set shared stack/environment variables
        id: set-stack-vars
        run: |
          # Set and export all shared variables for downstream jobs
          echo "FULL_STACK=${ENV_ESC}" >> $GITHUB_ENV
          trimmed_stack="${ENV_ESC##*/}"
          esc_environment="${ENV_ESC#*/}"
          esc_organization="${ENV_ESC%%/*}"
          echo "TRIMMED_STACK=$trimmed_stack" >> $GITHUB_ENV
          echo "ESC_ENVIRONMENT=$esc_environment" >> $GITHUB_ENV
          echo "ORGANIZATION=$esc_organization" >> $GITHUB_ENV
          # Set outputs for downstream jobs
          echo "FULL_STACK=$ENV_ESC" >> $GITHUB_OUTPUT
          echo "TRIMMED_STACK=$trimmed_stack" >> $GITHUB_OUTPUT
          echo "ESC_ENVIRONMENT=$esc_environment" >> $GITHUB_OUTPUT
          echo "ORGANIZATION=$esc_organization" >> $GITHUB_OUTPUT
      # Add any other shared setup steps here as needed
      - name: Install Dependencies
        run: yarn install --immutable
        working-directory: ./azure-deploy

  setup-acr-infra:
    needs: setup-environment
    runs-on: ubuntu-latest

    container:
      image: ghcr.io/catthehacker/ubuntu:act-22.04
    strategy:
      matrix:
        env_esc: ${{ fromJson(vars.ESC) }}
    env:
      ENV_ESC: ${{ matrix.env_esc }}
      PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
    outputs:
      ACR_USERNAME: ${{ steps.acr-creds.outputs.ACR_USERNAME }}
      ACR_PASSWORD: ${{ steps.acr-creds.outputs.ACR_PASSWORD }}
      ACR_URL: ${{ steps.acr-creds.outputs.ACR_URL }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: ./.github/actions/setup-node-yarn
      - name: Set ESC and Pulumi OIDC env vars
        id: set-esc-vars
        run: |
          echo "ESC_ACTION_ENVIRONMENT=$ENV_ESC" >> $GITHUB_ENV
          ORG="${ENV_ESC%%/*}"
          echo "organization=$ORG" >> $GITHUB_OUTPUT
        
      - uses: pulumi/esc-action@v1
      - name: Install Pulumi CLI
        uses: pulumi/setup-pulumi@v2
      - name: Install Pulumi Node.js SDK dependencies
        run: yarn install --immutable
        working-directory: ./azure-deploy
      - name: Select Pulumi stack
        working-directory: ./azure-deploy
        run: pulumi stack select acr-infra
      - name: Run Pulumi for ACR infra only
        working-directory: ./azure-deploy
        env:
          GITHUB_JOB: setup-acr-infra
        run: |
          pulumi up --yes
      - name: Export ACR credentials for next job
        id: acr-creds
        run: |
          echo "ACR_USERNAME=$(pulumi stack output acrUsernameOut)" >> $GITHUB_OUTPUT
          echo "ACR_PASSWORD=$(pulumi stack output acrPasswordOut)" >> $GITHUB_OUTPUT
          echo "ACR_URL=$(pulumi stack output registryUrlOut)" >> $GITHUB_OUTPUT

  setup-infra:
    needs: setup-acr-infra
    runs-on: ubuntu-latest

    container:
      image: ghcr.io/catthehacker/ubuntu:act-22.04
    strategy:
      matrix:
        env_esc: ${{ fromJson(vars.ESC) }}
    env:
      ENV_ESC: ${{ matrix.env_esc }}
      PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: ./.github/actions/setup-node-yarn
      - name: Set ESC and Pulumi OIDC env vars
        id: set-esc-vars
        run: |
          echo "ESC_ACTION_ENVIRONMENT=$ENV_ESC" >> $GITHUB_ENV
          ORG="${ENV_ESC%%/*}"
          echo "organization=$ORG" >> $GITHUB_OUTPUT
      - uses: pulumi/esc-action@v1
      - name: Install Pulumi CLI
        uses: pulumi/setup-pulumi@v2
      - name: Install Pulumi and Yarn
        uses: ./.github/actions/setup-pulumi-yarn
      - name: Select Pulumi stack
        working-directory: ./azure-deploy
        run: pulumi stack select ${{ env.ENV_ESC }}
      - name: Run Pulumi for infra (no apps)
        working-directory: ./azure-deploy
        env:
          GITHUB_JOB: setup-infra
        run: |
          pulumi up --yes

  build-images:
    needs: setup-environment
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - name: marketing-nginx
            dockerfile: mautic/marketing-nginx.dockerfile
          - name: marketing-mautic-app
            dockerfile: mautic/marketing-mautic-app.dockerfile
          - name: marketing-strapi-app
            dockerfile: launchpad/Dockerfile.prod
          - name: marketing-suitecrm-app
            dockerfile: suitecrm/marketing-suitecrm-app.dockerfile
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Build Docker image
        run: |
          docker buildx create --use
          docker buildx build --load -t ${{ matrix.name }}:build -f ${{ matrix.dockerfile }} .

  push-images:
    needs: [build-images, setup-acr-infra]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Login to Azure Container Registry
        run: echo ${{ needs.setup-acr-infra.outputs.ACR_PASSWORD }} | docker login ${{ needs.setup-acr-infra.outputs.ACR_URL }} -u ${{ needs.setup-acr-infra.outputs.ACR_USERNAME }} --password-stdin
      - name: Tag and push Docker images
        run: |
          docker tag marketing-nginx:build ${{ needs.setup-acr-infra.outputs.ACR_URL }}/marketing-nginx:latest
          docker tag marketing-mautic-app:build ${{ needs.setup-acr-infra.outputs.ACR_URL }}/marketing-mautic-app:latest
          docker tag marketing-strapi-app:build ${{ needs.setup-acr-infra.outputs.ACR_URL }}/marketing-strapi-app:latest
          docker tag marketing-suitecrm-app:build ${{ needs.setup-acr-infra.outputs.ACR_URL }}/marketing-suitecrm-app:latest
          docker push ${{ needs.setup-acr-infra.outputs.ACR_URL }}/marketing-nginx:latest
          docker push ${{ needs.setup-acr-infra.outputs.ACR_URL }}/marketing-mautic-app:latest
          docker push ${{ needs.setup-acr-infra.outputs.ACR_URL }}/marketing-strapi-app:latest
          docker push ${{ needs.setup-acr-infra.outputs.ACR_URL }}/marketing-suitecrm-app:latest

  setup-apps:
    needs: [setup-infra, push-images]
    runs-on: ubuntu-latest

    container:
      image: ghcr.io/catthehacker/ubuntu:act-22.04
    strategy:
      matrix:
        env_esc: ${{ fromJson(vars.ESC) }}
    env:
      ENV_ESC: ${{ matrix.env_esc }}
      PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: ./.github/actions/setup-node-yarn
      - name: Set ESC and Pulumi OIDC vars
        id: set-esc-vars
        run: |
          echo "ESC_ACTION_ENVIRONMENT=$ENV_ESC" >> $GITHUB_ENV
          ORG="${ENV_ESC%%/*}"
          echo "organization=$ORG" >> $GITHUB_OUTPUT
      - uses: pulumi/esc-action@v1
      - name: Install Pulumi CLI
        uses: pulumi/setup-pulumi@v2
      - name: Install Pulumi and Yarn
        uses: ./.github/actions/setup-pulumi-yarn
      - name: Select Pulumi stack
        working-directory: ./azure-deploy
        run: pulumi stack select ${{ env.ENV_ESC }}
      - name: Run Pulumi for apps only
        working-directory: ./azure-deploy
        env:
          GITHUB_JOB: setup-apps
        run: |
          pulumi up --yes

